parameter_dir: ../params
input_dir: ../data
label_dir: ../label
prediction_dir: ../ResultProb
pca_components: 30
patch_size: 25
batch_size: 2048
SVM_patch_size: 5
test_num: 500
test_models:
  Hybrid_BN_A:
    param: hybrid_BN_A.pth
    net: 1
    test: 1
  CNN2D:
    param: cnn_2d.pth
    net: 1
    test: 0
  CNN3D:
    param: cnn_3d.pth
    net: 1
    test: 0
  RF:
    param: RF.joblib
    net: 0
    test: 0
  RBF_SVM:
    param: RBF_SVM.joblib
    net: 0
    test: 0


